apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argocd-route.yaml

bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=release-0.12

patchesStrategicMerge:
- overlays/production/argocd-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-server-deploy.yaml

namespace: argocd
